name: AutoTasks

on:
  schedule:
    - cron: '0 12 * * *' # 每天中午12点执行
  workflow_dispatch: # 允许手动触发工作流程

jobs:
  run-java:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Run Java file
      run: |
        javac AutoTasks/src/Main.java
        java -cp AutoTasks/src Main
    - name: Commit and Push Changes
      run: |
        git config --global user.name 'inwinter04'
        git config --global user.email 'inwinter04@163.com'
        git add .
        git commit -m "Auto-update" -a || echo "No changes to commit"
        git push
